version: '3.7'

services:
 webapp:
   environment:
     - FLASK_ENV=production
     - FLASK_APP=/app/wsgi.py
     - PYTHONPATH=/app/
   volumes:
     - ./creds:/app/creds:ro
     - ./uwsgi.ini:/app/uwsgi.ini:ro
   ports:
     - target: 3031
       published: 5500
       protocol: tcp
       mode: host

    